[package]
name = "llamagguf-example"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
llm = { git = "https://github.com/rustformers/llm", features = ["llama"] }


